# TASK 1: DATA CLEANING AND PREPROCESSING

## 1. Importing libraries

In [55]:
import pandas as pd

In [56]:
df = pd.read_csv("Stock Prices Data Set Intern.csv")

## 2. Loading the Dataset

In [57]:
df.head()

  symbol      date      open      high       low     close    volume
0    AAL  1/2/2014   25.0700   25.8200   25.0600   25.3600   8998943
1   AAPL  1/2/2014   79.3828   79.5756   78.8601   79.0185  58791957
2    AAP  1/2/2014  110.3600  111.8800  109.2900  109.7400    542711
3   ABBV  1/2/2014   52.1200   52.3300   51.5200   51.9800   4569061
4    ABC  1/2/2014   70.1100   70.2300   69.4800   69.8900   1148391

In [58]:
df.shape

(497472, 7)

## 3. Checking for Missing Values

In [59]:
df.isnull().sum()

symbol     0
date       0
open      11
high       8
low        8
close      0
volume     0
dtype: int64

## Total No. of Empty Cells in the entire Data Set

In [60]:
df.isnull().sum().sum()

np.int64(27)

## 4. Handling Missing Values

In [61]:
df["open"] = df["open"].fillna(df["open"].median())

df["high"] = df["high"].fillna(df["high"].median())

df["low"] = df["low"].fillna(df["low"].median())

## Verifying Missing Values

In [62]:
df.isnull().sum()

symbol    0
date      0
open      0
high      0
low       0
close     0
volume    0
dtype: int64

Missing Value Treatment: The dataset contained missing values in the 'open', 'high', and 'low' price columns. Rather than removing the affected records, median imputation was applied to preserve the observations while reducing the influence of extreme stock-price values.

## 5. Checking for Duplicate Rows

In [63]:
df.duplicated().sum()

np.int64(0)

Duplicate Treatment: The dataset was checked for duplicate records using the duplicated() function. The result was 0, indicating that no duplicate rows were present. Therefore, no records were removed at this stage

## 6. Standardizing Data Formats

In [64]:
df.dtypes

symbol        str
date          str
open      float64
high      float64
low       float64
close     float64
volume      int64
dtype: object

## Standardizing the Date Format

In [65]:
df["date"] = pd.to_datetime(df["date"])

In [66]:
df.dtypes

symbol               str
date      datetime64[us]
open             float64
high             float64
low              float64
close            float64
volume             int64
dtype: object

Checking of Actual Dates

In [67]:
df["date"].head()

0   2014-01-02
1   2014-01-02
2   2014-01-02
3   2014-01-02
4   2014-01-02
Name: date, dtype: datetime64[us]

Checking for Invalid Dates

In [68]:
df["date"] = pd.to_datetime(df["date"], errors="coerce")

This will help us convert anything that isn't a valid date into NaT (missing date), allowing us to identify problematic entries instead of crashing.

In [69]:
df["date"].isnull().sum()

np.int64(0)

The `date` column was initially stored as a string data type. It was converted to the pandas datetime format to ensure consistent date handling and facilitate future time-series analysis.

## 7. Final Quality Check

In [70]:
print("Missing values:")
print(df.isnull().sum())

print("\nDuplicate rows:")
print(df.duplicated().sum())

print("\nData types:")
print(df.dtypes)

print("\nDataset shape:")
print(df.shape)

print("\nFirst 5 rows:")
display(df.head())

Missing values:
symbol    0
date      0
open      0
high      0
low       0
close     0
volume    0
dtype: int64

Duplicate rows:
0

Data types:
symbol               str
date      datetime64[us]
open             float64
high             float64
low              float64
close            float64
volume             int64
dtype: object

Dataset shape:
(497472, 7)

First 5 rows:

  symbol       date      open      high       low     close    volume
0    AAL 2014-01-02   25.0700   25.8200   25.0600   25.3600   8998943
1   AAPL 2014-01-02   79.3828   79.5756   78.8601   79.0185  58791957
2    AAP 2014-01-02  110.3600  111.8800  109.2900  109.7400    542711
3   ABBV 2014-01-02   52.1200   52.3300   51.5200   51.9800   4569061
4    ABC 2014-01-02   70.1100   70.2300   69.4800   69.8900   1148391

## 8. Saving The Clean Data Set

In [71]:
df.to_csv("cleaned_stock_prices.csv", index=False)

print("Cleaned dataset saved successfully!")

Cleaned dataset saved successfully!